### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by edgesofdarkness** [malganis93/BrlReCaptcha#3]
Hi

I implemented the module in my Zf2 Application but irrespective of whether I complete the captcha or not it always throws out "Value is required and can't be empty". Could you help?

**Comment by malganis93** [comment]
I can try to help. How have you implemented my module? By using the Form Helper or with a custom solution via the service manager? (see the README.md)

**Comment by edgesofdarkness** [comment]
Hi 

I did it without the service manager by implementing the view on my own!

**Comment by malganis93** [comment]
So you included the javascript https://www.google.com/recaptcha/api.js and added the element like this 

```
<div class="g-recaptcha" data-sitekey="<YOUR API PUBLIC KEY"></div>
```

? 
The error you've got comes from the Zend\Validator . The element has to be named "g-recaptcha-response", otherwise the validation will fail. The reason is, that the js from google creates a "virtual" input field with this name.

**Comment by edgesofdarkness** [comment]
Hi 

Thanks for your reply.

My form: 

 $element = new Captcha('g-captcha-response');
 $element->setCaptcha(new \BrlReCaptcha\ReCaptcha(array(
     'private_key' => '6LcDSg8TA........', //not included my full key
     'public_key' => '6LcDSg8TA........',  //not included my full key
     'theme' => 'dark'
 )));
 $this->add($element);

This is my view complete script: 

<div class="col-sm-6"></div>

```
            <div class="col-sm-6 col">
                <?php echo $this->formRow($form->get('g-captcha-response')) ?> 

            </div> 
```

**Comment by malganis93** [comment]
Well this should work. I am using the same way in my own application. I'll try to reproduce your issue. Which version are you using?

**Comment by edgesofdarkness** [comment]
Thanks!

Version of? your module? the latest one!

**Comment by edgesofdarkness** [comment]
Hi 

Could you reproduce the issue??

**Comment by malganis93** [comment]
Hi. Sorry for my bad response time, i was stuck in a big project. 
Unfortunately i was unable to reproduce your issue. I'm using exact the same code in my project and it is working fine. Are you sure, that the issue is caused by this module? Maybe you have another input with a bad validator? 

EDIT: Just saw your email. I'll check your code asap

**Comment by malganis93** [comment]
The issue was caused by my bad documentation. Please check 59009645fbebd21f97f2fc1b1d4b3350f85158f5

**Comment by ivok** [comment]
Hi guys. I installed this module and setup the Zfc-uzer to use this captcha element.

`'form_captcha_options' => array(
        'class' => 'BrlReCaptcha\ReCaptcha',
        'options' => array(
            'expiration' => 300,
            'timeout' => 300,
            'theme' => 'light',
            'private_key' => 'xxx',
            'public_key' => 'xxx'
        ),
    ),`

But Zfcuser Registration Form defines the captcha element with name "captcha" which fails validatio. If I change in ZFCUser Reg Form the element name to "g-recaptcha-repsonse" it works. But I dont want to change the vendor of course.

How to go around this problem?

**Comment by malganis93** [comment]
@ivok Please open a new issue for this problem. I've heart about this issue before, but i've never used the ZFC-User Module.
